### ISSUE TITLE
功能建议：自定义表情包功能

### ISSUE THREAD

**Issue by eric2788** [xfgryujk/blivechat#37]
刚刚在别的直播间看到发 (doge) 会出现狗头表情包，所以就想到了这个功能
主播可以加自己的表情包然后透过一些(關鍵字)来触发，显示在弹幕姬上
如果可以的话甚至可以复刻油管专属会限表情包功能
不知大佬意下如何

**Comment by xfgryujk** [comment]
1. 这个功能bilichat很早就有了，但是和blivechat定位不符所以一直没加
2. 如果要加，不好配置，用户理解起来困难。图床怎么选，如果允许用户上传图片会不会被滥用。配置塞到URL里会不会过长

**Comment by eric2788** [comment]
关于滥用问题，首先是建议仅限主播上传，而且有数量限制，并且是每位主播的表情包库分开，本地储存位置也有很多种方式

**Comment by xfgryujk** [comment]
1. 根本没办法判断当前用户是不是主播
2. 如果允许上传图片是不是可以把我的硬盘塞满

**Comment by kevinluo6188** [comment]
我觉得可以搞个图床(doge 在2021年03月16日 14:10，John Smith 写道： 



根本没办法判断当前用户是不是主播

如果允许上传图片是不是可以把我的硬盘塞满





—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/xfgryujk/blivechat/issues/37#issuecomment-799981898",

"url": "https://github.com/xfgryujk/blivechat/issues/37#issuecomment-799981898",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by eric2788** [comment]
等等，我是不是误会了什么
不是主播开exe来使用web app吗？
然后再捕获弹幕姬元素
为啥会分不清楚用户和主播

如果不是的话那抱歉我可能误会了

**Comment by eric2788** [comment]
啊，原来你说的是公共的
公共的话确实不行，我这边说的是私人的
